
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'APR BOOLEAN COMENTARIO DATE ENTRY FPR IGUAL NUMERO PALAVRA TEMPO VAR_NAME VIRGULAatrib : VAR_NAME IGUAL elementelement : NUMERO element : PALAVRA element : BOOLEANelement : DATEelement : TEMPO'
    
_lr_action_items = {'VAR_NAME':([0,],[2,]),'$end':([1,4,5,6,7,8,9,],[0,-1,-2,-3,-4,-5,-6,]),'IGUAL':([2,],[3,]),'NUMERO':([3,],[5,]),'PALAVRA':([3,],[6,]),'BOOLEAN':([3,],[7,]),'DATE':([3,],[8,]),'TEMPO':([3,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'atrib':([0,],[1,]),'element':([3,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> atrib","S'",1,None,None,None),
  ('atrib -> VAR_NAME IGUAL element','atrib',3,'p_atrib','tomlex.py',46),
  ('element -> NUMERO','element',1,'p_element_num','tomlex.py',51),
  ('element -> PALAVRA','element',1,'p_element_palavra','tomlex.py',55),
  ('element -> BOOLEAN','element',1,'p_element_bool','tomlex.py',59),
  ('element -> DATE','element',1,'p_element_data','tomlex.py',63),
  ('element -> TEMPO','element',1,'p_element_tempo','tomlex.py',67),
]
